name: Deployment Notifications

on:
  workflow_run:
    workflows: ["Deploy Sandbox", "Deploy Staging", "Deploy Production"]
    types: [completed, requested]

jobs:
  on-started:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'requested' }}

    steps:
      - uses: actions/checkout@v2

      - name: Slack Started Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Actions
          SLACK_COLOR: "#3B82F6"
          SLACK_ICON: "https://iconape.com/wp-content/png_logo_vector/laravel-vapor.png"
          SLACK_MESSAGE: "Build queued"
          SLACK_FOOTER: "Action: ${{ github.event.workflow_run.name }}"

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Slack Completed Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Actions
          SLACK_ICON: "https://iconape.com/wp-content/png_logo_vector/laravel-vapor.png"
          SLACK_MESSAGE: "Build Succeeded :white_check_mark:"
          SLACK_FOOTER: "Action: ${{ github.event.workflow_run.name }}"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - uses: actions/checkout@v2

      - name: Slack Failure Notification
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Actions
          SLACK_ICON: "https://iconape.com/wp-content/png_logo_vector/laravel-vapor.png"
          SLACK_COLOR: "failure"
          SLACK_MESSAGE: "Build Failed :x:"
          SLACK_FOOTER: "Action: ${{ github.event.workflow_run.name }}"
